# Generated by Django 3.2.6 on 2021-09-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Running', 'Running'), ('Cancelled', 'Cancelled'), ('Stopped', 'Stopped'), ('Failed', 'Failed')], max_length=255),
        ),
    ]
