from django.urls import path, include
from rest_framework import views
from .views import (JobList, CreateJobs, StopJob ,CancelJob, ResumeJob, RestartJob, ListRunningJobs, 
                    LastTenJobs, GetFinishedJobs, GetDetailedJobInfo, GetLogs, GetAllLogs, UserList
                   )

urlpatterns = [
    path("getjobs/",
        JobList.as_view(),
        name="job-list-view"),
    path("createjob/",
        CreateJobs.as_view(),
        name="create-job-view"),
    path("canceljob/<job_id>",
        CancelJob.as_view(),
        name="cancel-job-view"),
    path("stopjob/<job_id>",
        StopJob.as_view(),
        name="stop-job-view"),
    path("resumejob/<job_id>",
        ResumeJob.as_view(),
        name="resume-job-view"),
    path("restartjob/<job_id>",
        RestartJob.as_view(),
        name="restart-job-view"),
    path("runningjobs/",
        ListRunningJobs.as_view(),
        name="running-job-view"),
    path("lastjobs/<str:user_name>",
        LastTenJobs.as_view(),
        name="last-job-view"),
    path("getfinishedjobs/",
        GetFinishedJobs.as_view(),
        name="get-finished-job-view"),
    path("getdetailedjob/<job_id>",
        GetDetailedJobInfo.as_view(),
        name="get-detailed-job-view"),
    path("getlogs/<job_id>",
        GetLogs.as_view(),
        name="get-logs-view"),
    path("getalllogs/",
         GetAllLogs.as_view(),
        name="get-all-logs-view"),
    path("userlist/",
         UserList.as_view(),
        name="get-user-list-view"),
]
